---
- name: Install Apache WebServer
  hosts: all
  become: yes
  remote_user: ubuntu
  tasks: 
    - name: install apache
      when: ansible_distribution == "Ubuntu"
      apt:
        name: apache2
        state: present
    - name: run apache
      systemd:
        name: apache2
        state: restarted
        enabled: 
