---
- name: Install Apache WebServer
  hosts: all
  become: yes
  remote_user: ubuntu
  tasks: 
    - name: install apache
      when: ansible_distribution == "Ubuntu"
      yum:
        name: httpd
        state: present
      
