---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install multiple packages
      when: ansible_distribution == "Ubuntu" 
      package:
        name: "{{ item }}"
        state: present
      with_items:
       - telnet
      
