#On AWS manage the security group which was attached to hosts
#You will need to add:
#  - Custom TCP rule with port number which you want
#  - Specify source: anywhere


#On AWX before running the job-template make sure you will add variables under "EXTRA VARIABLES"
#---
#host: IP or hostname             example: all or ipaddr or centos
#port_line: Port ##              example: "Port 8875"
#port: port number               example: "8875"
#protocol: give protocol name    example: "TCP"

#Make sure you have enabled option "PROMPT ON LAUNCH" of extra variables

#In the host machine please run the following command to see current ssh port:
#   sudo netstat -tlnp | grep ssh


---
- name: ssh-port changing
  hosts: "{{ host }}"                          #Please specify the host
  #gather_facts: no
  remote_user: root
  tasks:
  - name: Setup alternate SSH port
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^Port"
      line: "{{ port_line }}"                  #Please specify the port_line
      #line: "Port 8875"

  - name: Setup selinux for alternate SSH port
    seport:
      ports: "{{ port }}"                      #Please provide port number which you wanna alternate the default 22
      #ports: "8875"
      proto: "{{ protocol }}"                  #Please provide protocol
      #proto: "tcp"
      setype: "ssh_port_t"
      state: "present"

  - name: Restart sshd
    service:
      name: sshd                               #This server need to be changed
      state: restarted
